# Generated by Django 6.0.5 on 2026-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(unique=True)),
                ('marks', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
